- name: Install web
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    
    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
